name: tests

on:
  push:
    branches:
      - "*"
    # not on tags
  pull_request:

env:
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: "1"

jobs:
  cargo_tests:
    name: ${{ matrix.os }} ${{ matrix.rust_channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
        rust_channel: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust_channel }}
    - run: cargo test
    - run: cargo test --no-default-features
    - run: cargo test --all-features
    # One more run with a very long test duration for test_wait_try_wait_race.
    - name: run test_wait_try_wait_race for 5 minutes
      run: cargo test --all-features
      env:
        SHARED_CHILD_RACE_TEST_SECONDS: 300
